eureka:
  instance:
    hostname: vmakj231
  client:
    service-url:
      defaultZone: http://admin:vma123456@vmakj115:51001/eureka,http://admin:vma123456@vmakj226:51001/eureka,http://admin:vma123456@www.chennh.com:51001/eureka

server:
  host: 47.92.122.231