eureka:
  instance:
      hostname: www.chennh.com
  client:
    service-url:
      defaultZone: http://admin:vma123456@vmakj231:51001/eureka,http://admin:vma123456@vmakj115:51001/eureka,http://admin:vma123456@vmakj226:51001/eureka

server:
  host: www.chennh.com